[package]
name = "pubgrub_opam"
version = "0.1.0"
edition = "2021"

[dependencies]
pubgrub = "0.3.0"
rustc-hash = "=1.1.0"
itertools = "0.10.1"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
walkdir = "2.3"
